arm/pci: select HAS_PCI_MSI
Currently, there is some pdev data that is not getting properly
initialized (in particular pdev->msi_maxvec). As a result, when passing
through a PCI device with 2 or more MSI vectors to a domU, only the
first MSI vector gets signaled in the domU. When building with
PCI_PASSTHROUGH enabled, also select HAS_PCI_MSI to enable the proper
pdev state initialization in Xen. This resolves the issue with passing
through devices with 2 or more MSI vectors.

Signed-off-by: Stewart Hildebrand <stewart.hildebrand@amd.com>
---
Resolves https://jira.xilinx.com/browse/CR-1193355

Squashed commit:

xen/arm: fix build failure with XSM and PCI_PASSTHROUGH

When both CONFIG_XSM=y and CONFIG_PCI_PASSTHROUGH=y are selected
simultaneously, we observe the following build errors:

xsm/flask/hooks.c: In function ‘get_irq_sid’:
xsm/flask/hooks.c:129:46: error: ‘struct msi_desc’ has no member named ‘dev’
  129 |         if ( desc->msi_desc && desc->msi_desc->dev )
      |                                              ^~
xsm/flask/hooks.c:131:49: error: ‘struct msi_desc’ has no member named ‘dev’
  131 |             struct pci_dev *dev = desc->msi_desc->dev;
      |                                                 ^~
xsm/flask/hooks.c: In function ‘flask_map_domain_msi’:
xsm/flask/hooks.c:957:31: error: invalid use of undefined type ‘const struct msi_info’
  957 |     uint32_t machine_bdf = msi->sbdf.sbdf;
      |                               ^~

Define the missing type and add the missing field to struct msi_desc.

Fixes: ("arm/pci: select HAS_PCI_MSI")
Reported-by: Michal Orzel <michal.orzel@amd.com>
Signed-off-by: Stewart Hildebrand <stewart.hildebrand@amd.com>
Reviewed-by: Stefano Stabellini <stefano.stabellini@amd.com>
CR: CR-1197876