xen/dt: create dom0 and domU DT nodes for vPCI with correct addresses
Depending on whether the guest is using vPCI or not, and whether the
domain is using host layout or not, generate the appropriate device tree
nodes for the guest and handle the right MMIO regions traps.

Signed-off-by: Stefano Stabellini <stefano.stabellini@amd.com>
Signed-off-by: Stewart Hildebrand <stewart.hildebrand@amd.com>
---
Reviewed-by: Stefano Stabellini <stefano.stabellini@amd.com> # xlnx downstream
* rebase on 8d2c3ab18cc1 ("arm/dom0less: put dom0less feature code in a separate module")
* rebase on smmu pci series v10

Commit squash:

arm/gic-v3-its: fix build failure with CONFIG_HAS_ITS=y

When building with CONFIG_HAS_ITS=y, we may observe the following build
error with some versions of gcc in certain build configurations:

| arch/arm/gic-v3-its.c: In function 'gicv3_its_make_emulated_dt_node':
| arch/arm/gic-v3-its.c:1060:5: error: 'its_base' may be used uninitialized [-Werror=maybe-uninitialized]
|  1060 |     dt_child_set_range(&cells, GUEST_ROOT_ADDRESS_CELLS, GUEST_ROOT_SIZE_CELLS,
|       |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|  1061 |                        its_base, its_size);
|       |                        ~~~~~~~~~~~~~~~~~~~
| arch/arm/gic-v3-its.c:1009:14: note: 'its_base' was declared here
|  1009 |     uint64_t its_base;
|       |              ^~~~~~~~

Fix the build error by initializing the variable. Return in case a
hardware ITS is not found.

Fixes: ("xen/dt: create dom0 and domU DT nodes for vPCI with correct addresses")
Signed-off-by: Stewart Hildebrand <stewart.hildebrand@amd.com>
---
v2: add list_empty(&host_its_list) check

https://jira.xilinx.com/browse/CR-1193355