xen/pci: Add cf_check to some functions
These seem to be missing.
drivers/passthrough/pci.c: In function 'add_discovered_pci_devices':
drivers/passthrough/pci.c:1218:26: error: passing argument 1 of 'pci_segments_iterate' from incompatible pointer type [-Werror=incompatible-pointer-types]
 1218 |     pci_segments_iterate(_add_discovered_pci_devices, NULL);
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                          |
      |                          int (__attribute__((nocf_check)) *)(struct pci_seg *, void *)
drivers/passthrough/pci.c:109:11: note: expected 'int (*)(struct pci_seg *, void *)' but argument is of type 'int (__attribute__((nocf_check)) *)(struct pci_seg *, void *)'
  109 |     int (*handler)(struct pci_seg *pseg, void *arg), void *arg)
      |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Jason Andryuk <jason.andryuk@amd.com>